### ISSUE TITLE
Feature Request: Highlight by RegExp

### ISSUE THREAD

**Issue by DanielBuecherl** [wayou/vscode-todo-highlight#33] opened 2017-05-04 10:37 UTC
Awesome Extension!
I have a small request. 

I’d like to match different keywords by one custom highlight rule (like matching "TODO:" and "TODO" together). 

This would have two benefits:
* Less setup effort for the configuration, since currently you have to define a rule for each item. If they had the same rule, this wouldn’t be necessary.
* Simplification of match listing. Matches found for either of these keywords would show up in the same highlight search.

Example: 
A hint/note that something in my code needs review is either marked with "DB" or "Look". One is addressed directly towards me, while the other one is for all members. Since I have to take a look at both, it would simplify things if they showed up together. Currently, I have to define separate rules for both keywords. When searching during the correction process, I have to do it twice.

Proposal for solution: 
* Add an additional optional parameter for custom keywords: "regExp": string
* When present, only strings matching that RegExp will be highlighted ("text"-property has another meaning in that case)
* When listing highlights, it displays the "text"-property in the dropdown (which behaves like the name for this rule)
* Using RegExp even more complex matches would be possible. This means you could restrict it to comments only ("\/\/ *DB" would match "//DB"  and "// DB") avoiding in-code matches.

**Comment by wayou** [comment] 2017-05-05 15:13
Duplicate of #28.
Originally when I came across the idea for this extension I want things be simple, so the design is based on keyword per keyword.
However, have to say RexExp can meet most requests. I will consider to implement but can't  guarantee when to ship. PR is welcomed.

**Comment by DanielBuecherl** [comment] 2017-05-06 10:52
Didn't see #28 when looking through the closed issues. 
It always grows bigger than expected, hmm?
In my opinion, RegEx is mandatory for a programmer. And the way described above, it's strictly optional to use it in your extension. Anybody not capable could still configure it the "normal" way.

**Closed** 2017-05-17 10:24 UTC
Labels: duplicate, enhancement

**Comment by andys8** [comment] 2017-07-27 10:59
@wayou Ist there a reason the default is `TODO:` instead of `TODO`?

**Comment by wayou** [comment] 2017-07-27 12:22
@andys8 just a convention that `:` followed with content

**Comment by andys8** [comment] 2017-07-27 12:40
Okay, because I was quite surprised it is necessary :)

**Comment by legrandmawak** [comment] 2019-01-21 21:06
Hi !
is it possible that the Highlight list (output) is only those with the specific handle TODO: ?
because we are using a special rules that it requires to put initials at the end of the TODO string, 
	"todohighlight.keywordsPattern": ".*\\s?(TO\\s?DO|FIXME|CODE\\s?REVIEW)\\s?([A-Z]{2,4}).*:.*",
using this make only the todos prefixed with 2 to 4 char highlighted (works great). 
but when we display the list of todos only those starting with explicit 'TODO:' shows....
is it intended ? 

thanks
(notice in the attachement that the second TODO isn't hightlighted
![image](https://user-images.githubusercontent.com/46906409/51498961-7531ab00-1d96-11e9-99c0-b19d3c1cd80c.png)
