### ISSUE TITLE
Highlight entire multi-line comments

### ISSUE THREAD

**Issue by MaidenJD** [wayou/vscode-todo-highlight#60] opened 2017-09-14 20:30 UTC
Hopefully this'll be a simple feature to add. Sometimes when I writing notes or TODO's, I'll do them at the top of a file in a list-form multiline comment. I think it would be a nice feature to be able to highlight the entire comment from opening chars to closing chars.0

I understand this may hinder drawing the highlight shape around the text and solving a wrapping issue maybe, but it's a feature I would love to see, and it's definitely something no other todo extension appears to have looked into (Feel free to correct me if I'm wrong on that!).

I absolutely love this add-on, it lets me keep my code organized, whilst still having a nice aesthetic! My hope is that this idea may help make it even better!

**Comment by wayou** [comment] 2017-09-23 11:08
The problem is how to determine the end of the annotations in varies scenarios. Of course we can detect closing chars added manually, but that's not common for most users.

**Closed** 2017-09-23 11:10 UTC
